# 📓 Assignment 4 — Linear Algebra Fundamentals

*Vectors & Matrices for Everyday Coding*



## Welcome back, intrepid coder! 🚀
In this notebook-styled brief you’ll move from single-direction vectors to multi-direction matrices—core tools behind graphics, robotics, optimisation and (of course) machine-learning. Each mini-section mixes quick notes, a tiny real-world scenario, and hands-on # TODO code shaped for beginners.


## 🧭 Vectors 101

| Concept             | Quick reminder                                  |
|---------------------|--------------------------------------------------|
| Representation      | 1-D NumPy array — `np.array([x, y, z])`         |
| Length (norm)       | `np.linalg.norm(v)`                             |
| Dot / inner product | `v.dot(w)` or `np.inner(v, w)`                  |
| Unit vector         | `v / np.linalg.norm(v)`                         |


In [ ]:
# Run once per session
import numpy as np

# TODO 1: create a 3-D vector named v
v = np.array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[10,20,30], [40,50,60], [70,80,90]],
    [[100,200,300], [400,500,600], [700,800,900]],
])
# TODO 2: print its length
print(np.linalg.norm(v))
# TODO 3: build a second vector w and output the dot product
w = np.array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[10,20,30], [40,50,60], [70,80,90]],
    [[100,200,300], [400,500,600], [700,800,900]],
])
print(np.dot(v, w))

1696.6982642768278
[[[[     30      36      42]
   [    300     360     420]
   [   3000    3600    4200]]

  [[     66      81      96]
   [    660     810     960]
   [   6600    8100    9600]]

  [[    102     126     150]
   [   1020    1260    1500]
   [  10200   12600   15000]]]


 [[[    300     360     420]
   [   3000    3600    4200]
   [  30000   36000   42000]]

  [[    660     810     960]
   [   6600    8100    9600]
   [  66000   81000   96000]]

  [[   1020    1260    1500]
   [  10200   12600   15000]
   [ 102000  126000  150000]]]


 [[[   3000    3600    4200]
   [  30000   36000   42000]
   [ 300000  360000  420000]]

  [[   6600    8100    9600]
   [  66000   81000   96000]
   [ 660000  810000  960000]]

  [[  10200   12600   15000]
   [ 102000  126000  150000]
   [1020000 1260000 1500000]]]]


### 🚁 Practical Scenario — “Drone hop”
A mini-drone lifts off at (2 m, 1 m) and lands at (7 m, 4 m).
Calculate its displacement vector, travel distance, and orientation along the x-axis.

In [ ]:
p_start = np.array([2, 1])
p_end   = np.array([7, 4])

# displacement
d = p_end - p_start          # ➡️ vector from start to end
dist = np.linalg.norm(d)     # 🏁 distance travelled
unit = d / dist              # ↗️ unit direction
dot_x = d.dot(np.array([1, 0]))  # projection on x-axis

print("Displacement:", d)
print("Distance:", dist)
print("Unit direction:", unit)
print("Dot-product with x-axis:", dot_x)


Displacement: [5 3]
Distance: 5.830951894845301
Unit direction: [0.85749293 0.51449576]
Dot-product with x-axis: 5


## 🔢 Matrices 101

| Operation              | NumPy one-liner                                  |
|------------------------|--------------------------------------------------|
| Transpose              | `A.T`                                            |
| Determinant            | `np.linalg.det(A)`                               |
| Inverse                | `np.linalg.inv(A)` (works only if `det(A) ≠ 0`)  |
| Matrix-vector multiply | `A @ v`                                          |
| Matrix-matrix multiply | `A @ B`                                          |


In [ ]:
# TODO 4: build a 2×2 matrix A
A = np.array([
    [1, 2],
    [3, 4]
])
# TODO 5: print its determinant
print(np.linalg.det(A))
# TODO 6: if invertible, compute and print A_inv
print(np.linalg.inv(A))


-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


### 🎯 Practical Scenario — “Rotate that hop”
Rotate the drone’s displacement vector 30° counter-clockwise, then verify that the inverse rotation brings it back.

In [ ]:
theta = np.deg2rad(30)          # 🔄 convert degrees to radians
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])

det_R = np.linalg.det(R)        # should be 1.0 (pure rotation)

d_rot  = R @ d                  # rotated displacement
d_back = np.linalg.inv(R) @ d_rot

print("Rotation matrix determinant:", det_R)
print("Rotated vector:", d_rot)
print("Back-rotated equals original?", np.allclose(d_back, d))


Rotation matrix determinant: 1.0
Rotated vector: [2.83012702 5.09807621]
Back-rotated equals original? True
