# 🔥 Assignment: Exploring PyTorch

<p align="center">📢⚠️📂  </p>

<p align="center"> Please name your file using the format: <code>assignmentName_nickname.py/.ipynb</code> (e.g., <code>project1_ali.py</code>) and push it to GitHub with a clear commit message.</p>

<p align="center"> 🚨📝🧠 </p>

------------------------------------------------



## 🎯 Goal
This assignment evaluates your basic skills in using PyTorch, focusing on tensors, autograd, and a small training loop.



### 1️⃣ Setup and Basics
**Task:**

* Install PyTorch and check its version.

* Create a 2D tensor and print it.

In [ ]:
import torch

print("PyTorch version:", torch.__version__)
x = torch.tensor([[1., 2.], [3., 4.]])
print("Tensor x:\n", x)


PyTorch version: 2.6.0+cu124
Tensor x:
 tensor([[1., 2.],
        [3., 4.]])


In [ ]:
# Your turn:
# Create another tensor y of the same shape with values [[5, 6], [7, 8]].
y = torch.tensor([[5., 6.], [7., 8.]])
print("Tensor y:\n", y)

Tensor y:
 tensor([[5., 6.],
        [7., 8.]])


### 2️⃣ Tensor Operations 🧮
**Task:** Perform addition and matrix multiplication.

In [ ]:
z = x + y
print("Addition:\n", z)

mat_mul = x @ y
print("Matrix Multiplication:\n", mat_mul)


Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])


In [ ]:
# Your turn:
# Perform element-wise multiplication (x * y) and print the result.
element_wise_mul = x * y
print("Element-wise Multiplication:\n", element_wise_mul)

Element-wise Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])


### 3️⃣ Autograd and Gradients ⚙️
**Task:** Enable gradient tracking and compute derivatives.

In [ ]:
a = torch.tensor(3.0, requires_grad=True)
b = (a ** 2) + 2 * a + 1
b.backward()
print("Gradient of b wrt a:", a.grad)


Gradient of b wrt a: tensor(8.)


In [ ]:
# Your turn:
# Create a tensor p with value 2.0 (requires_grad=True) and compute the gradient of q = p^3 + 4p.
p = torch.tensor(2.0, requires_grad=True)
q = p**3 + 4*p
q.backward()
print("Gradient of q wrt p:", p.grad)

Gradient of q wrt p: tensor(16.)


### 4️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (2, 3) and find its max and min.

In [ ]:
rand_tensor = torch.rand((2, 3))
print("Random Tensor:\n", rand_tensor)
print("Max:", torch.max(rand_tensor))
print("Min:", torch.min(rand_tensor))

Random Tensor:
 tensor([[0.6153, 0.5978, 0.6081],
        [0.7367, 0.5628, 0.2782]])
Max: tensor(0.7367)
Min: tensor(0.2782)


### 5️⃣ Mini Training Loop 🤖
**Task:** Train a simple linear model y = wx + b using gradient descent.

In [ ]:
# Data
x_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0]])

# Model
w = torch.randn(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# Training
learning_rate = 0.01
for epoch in range(100):
    y_pred = w * x_train + b
    loss = torch.mean((y_pred - y_train) ** 2)
    loss.backward()

    # Update
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()

print("Trained weight:", w.item())
print("Trained bias:", b.item())

Trained weight: 1.8676393032073975
Trained bias: 0.30086851119995117


### 6️⃣ Bonus ⚡
* Convert a PyTorch tensor to a NumPy array.

* Convert it back to a PyTorch tensor.

In [ ]:
# To do
# Convert a PyTorch tensor to a NumPy array.
numpy_array = x.numpy()
print("Tensor converted to NumPy array:\n", numpy_array)

# Convert it back to a PyTorch tensor.
pytorch_tensor = torch.from_numpy(numpy_array)
print("NumPy array converted back to PyTorch tensor:\n", pytorch_tensor)

Tensor converted to NumPy array:
 [[1. 2.]
 [3. 4.]]
NumPy array converted back to PyTorch tensor:
 tensor([[1., 2.],
        [3., 4.]])
