# 🧠 Assignment: Getting Started with TensorFlow


<p align="center">📢⚠️📂  </p>

<p align="center"> Please name your file using the format: <code>assignmentName_nickname.py/.ipynb</code> (e.g., <code>project1_ali.py</code>) and push it to GitHub with a clear commit message.</p>

<p align="center"> 🚨📝🧠 </p>

------------------------------------------------



## 🎯 Goal
This assignment evaluates your basic skills in using TensorFlow, including creating tensors, performing operations, and building a simple model.

### 1️⃣ Setup and Basics
**Task:**

* Install TensorFlow and verify the version.
* Create a simple tensor and print it.

In [ ]:
# Example snippet
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
a = tf.constant([[1, 2], [3, 4]])
print("Tensor a:\n", a)


TensorFlow version: 2.19.0
Tensor a:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
# Your turn:
# Create a tensor b with values [[5, 6], [7, 8]] and print its shape.
b = tf.constant([[5, 6], [7, 8]])
print("Tensor b:\n", b)
print("Shape of tensor b:", b.shape)

Tensor b:
 tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
Shape of tensor b: (2, 2)


### 2️⃣ Tensor Operations
**Task:** Perform element-wise addition and multiplication.

In [ ]:
# Example snippet
c = a + b
print("Addition:\n", c)

d = a * b
print("Multiplication:\n", d)

Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [ ]:
# Your turn:
# Compute a @ b (matrix multiplication) and print the result.
e = tf.matmul(a, b)
print("Matrix Multiplication:\n", e)

Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### 3️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (3, 3) from a normal distribution and print its mean and standard deviation.

In [ ]:
# Example snippet
random_tensor = tf.random.normal([3, 3])
print("Random Tensor:\n", random_tensor)
print("Mean:", tf.reduce_mean(random_tensor))
print("Std Dev:", tf.math.reduce_std(random_tensor))

Random Tensor:
 tf.Tensor(
[[ 0.62120837  0.28564683 -0.07717083]
 [-2.1085153  -0.13691652 -0.8273065 ]
 [ 1.1213512   0.24208722 -0.49189565]], shape=(3, 3), dtype=float32)
Mean: tf.Tensor(-0.15239014, shape=(), dtype=float32)
Std Dev: tf.Tensor(0.88011736, shape=(), dtype=float32)


### 4️⃣ Building a Simple Model 🤖
**Task:** Build a single-layer neural network using tf.keras.Sequential.

In [ ]:
# Example snippet
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])
model.summary()


In [ ]:
# Your turn:
# Add another dense layer with 5 neurons and relu activation.
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])
model.add(tf.keras.layers.Dense(5, activation='relu'))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12 (48.00 B)

 Trainable params: 12 (48.00 B)

 Non-trainable params: 0 (0.00 B)

### 5️⃣ Bonus ⚡
* Create a tensor with values from 0 to 9 (inclusive).

* Reshape it to shape (2, 5).

* Pint the reshaped tensor.

In [ ]:
# To do
# Create a tensor with values from 0 to 9 (inclusive).
tensor_0_to_9 = tf.range(10)
print("Original tensor:", tensor_0_to_9)

# Reshape it to shape (2, 5).
reshaped_tensor = tf.reshape(tensor_0_to_9, (2, 5))

# Print the reshaped tensor.
print("Reshaped tensor:\n", reshaped_tensor)

Original tensor: tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
Reshaped tensor:
 tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
